# Generated by Django 4.1.3 on 2023-03-20 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_infocontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infocontact',
            name='numero',
            field=models.IntegerField(max_length=8),
        ),
    ]
